### ISSUE TITLE
Handle incoming nonce

### ISSUE THREAD

**Issue by JohannesEbke** [TNG/gpg-validation-server#10]
- Load associated public key
- Sign correct UserID of public key
- Construct email with signed public key

Add confirm_nonce command to cli

**Comment by JohannesEbke** [comment]
Implemented a preliminary working implementation for a fake request with nonce 32ff00000000000032ff00000000000032ff00000000000032ff000000000123
in 22c80b225adf80927edb0fff75d70fa3c724f985

**Comment by Pharb** [comment]
I'll refactor this a bit, to get the fully working prototype.
