### ISSUE TITLE
Add server feature to cli

### ISSUE THREAD

**Issue by JohannesEbke** [TNG/gpg-validation-server#11]
- Add a noncelistener HTTP server :white_check_mark: 
- Start SMTP server :white_check_mark: 
- Handle mails and Nonces

**Comment by JohannesEbke** [comment]
Preliminary NonceListener in db7d6fe41daeedab5c84a8adfab8b7c458e6d6ff

**Comment by JohannesEbke** [comment]
Full chain working with SMTP and HTTP servers in 0da4bd3ca1dd536284b79eec5292147346d59bc8

Tests are still missing, and refactoring is necessary.

**Comment by Pharb** [comment]
Looks great already 👍 Is it ok if I push onto `fullchain`?
Are you currently refactoring? I'll cleanup main.go and work out the nonce generation as part of #9.
