### ISSUE TITLE
Support incoming encrypted mails

### ISSUE THREAD

**Issue by JohannesEbke** [TNG/gpg-validation-server#21]

**Comment by v-maurer** [comment]
The main problem lies in verifying the signature of incoming mails: if we do not already have the public key of the sender, the openpgp package does not (cannot) check the signature and actually does not even save the MessageDetails.Signature attribute. So the logic ReadMessage -> save Signature -> [some time] -> verify Signature against now known public key is not easily possible without again calling ReadMessage.
