### ISSUE TITLE
Mail parsing

### ISSUE THREAD

**Issue by JohannesEbke** [TNG/gpg-validation-server#6]
Parse a text mail, providing the following information:
- Attached public key
- Is the message correctly signed with the attached key?

**Comment by JohannesEbke** [comment]
Currently, sending a mail from enigmail, I get an error about the signature content type. Mine is: 
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="8EHGnptbThJdkkPimWIKoBJhGTa9vIlf7"

**Comment by Pharb** [comment]
@JohannesEbke I'm working on this currently as part of #9. I'm trying to get a pull request ready that might resolve your issue.
